global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ingestion-service'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['ingestion-service:8082']

  - job_name: 'device-management-service'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['device-management-service:8081']

  - job_name: 'analytics-service'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['analytics-service:8084']

  - job_name: 'processing-service'
    metrics_path: /q/metrics
    static_configs:
      - targets: ['processing-service:8083']
